.gitignore, README.md, cypress.config.js, cypress/e2e/footer.cy.js, cypress/e2e/signup.cy.js, cypress/support/e2e.js, package-lock.json, package.json
- Install Cypress
- Add e2e test examples
=> install Cypress with examples

.github/cypress.yml, README.md, cypress.config.js, cypress/e2e/home.cy.js, package-lock.json, package.json
New demo test plus addition of actions yml.
=> Markodonnell deriv patch 1

.github/workflows/cypress.yml
=> Update cypress.yml with repository_dispatch

.github/workflows/cypress.yml, cypress/e2e/smoke/aboutUs.cy.js, cypress/e2e/smoke/home.cy.js, cypress/e2e/smoke/legal.cy.js, cypress/e2e/smoke/markets.cy.js, cypress/e2e/smoke/partners.cy.js, cypress/e2e/smoke/resources.cy.js, cypress/e2e/smoke/signups.cy.js, cypress/e2e/smoke/trade.cy.js, cypress/support/e2e.js
=> Markodonnell deriv patch 5

.github/workflows/cypress_cloud_manual.yml, .gitignore, cypress.config.js, cypress/e2e/full/login.cy.js, cypress/e2e/smoke/home.cy.js, package-lock.json, package.json
=> Rework on tests plus added a new manual workflow action

cypress/e2e/smoke/home1.cy.js
=> Mitra/ fix ETF case on close button in responsive

cypress/e2e/smoke/home1.cy.js, cypress/e2e/smoke/home2.cy.js
By change of new card to remove deriv ez in below PR , we need to remove deriv ez mentions in our tests
https://github.com/binary-com/deriv-com/pull/5795
=> Mitra/ fix removal of deriv ez

cypress/e2e/smoke/home3.cy.js, cypress/e2e/smoke/home4.cy.js
Update test for this auto-typing text
=> Fasih/: Updated full keywords

cypress.config.js, cypress/e2e/smoke/footerEU.cy.js, cypress/fixtures/example.json, cypress/support/POM/commonEuPage.js
Test for footer EU QATEST-1422 
Half test cases are covered for footer EU (responsive)
Changed Project structure to POM
=> chore: test for footer EU

cypress/e2e/smoke/footerEU.cy.js, cypress/support/POM/commonEuPage.js
All test cases are passing locally, but they are failing on cypress cloud.
Inside error [https://cloud.cypress.io/projects/16kef2/runs/836/overview/f43f034a-e706-4f87-a291-af5ab5d6817a?roarHideRunsWithDiffGroupsAndTags=1]
a suggestion was given to add {force:true} added it on few places where test cases might fail.
=> fixed failing test cases

cypress.config.js, cypress/e2e/smoke/footerEU.cy.js, cypress/support/POM/commonEuPage.js
1. Fixed failures by dividing large test blocks in two tests.
2.  Also added more test cases for Task https://app.clickup.com/t/20696747/QATEST-1422
3. PDF opening related test cases are also been added.
=> QAtest-1422Remainingtests

cypress.config.js, cypress/support/e2e.js, cypress/support/livepricing.js
Adding the url in config file and changing the name of commands.js file to livepricing.js to be more specific as that file has functions for rowlivepricing.cy.js and eulivepricing.cy.js
=> fix_in_configfile

cypress/e2e/smoke/signUpEmailValidation.cy.js, cypress/support/e2e.js, cypress/support/helper.js
This PR has code for email validation in signup section
https://app.clickup.com/t/20696747/DERC-2244
=> signupemailvalidation

cypress/e2e/smoke/allHomeHeader.cy.js, cypress/support/POM/homePage.js
Fixed allHomeHeader test cases, added elements in common class for global access.
=> fixed-allHomeHeader

package-lock.json
we accidentally removed the package lock file without knowing it has dependency in the project. This PR is to add it back
=> add package lock

cypress/e2e/smoke/allHomeBanner.cy.js, cypress/e2e/smoke/euFooter.cy.js, cypress/support/POM/homePage.js
This PR is to fix the following tests due to the new changes in staging:
- QATEST-1315 & 1310 - Validate Hero banner message
- QATEST-1422 Footer EU Responsive
PR test result - https://cloud.cypress.io/projects/16kef2/runs/1429/overview?roarHideRunsWithDiffGroupsAndTags=1
Clickup card: https://app.clickup.com/t/86bwwzcxz
=> fix homepage banner and eu footer

cypress.config.js, cypress/e2e/smoke/signUpCompleteFlow.cy.js, cypress/e2e/wip/signUpCompleteFlow.cy.js, cypress/support/e2e.js
Card - https://app.clickup.com/t/20696747/DERC-2257
=> DerivComSignupflow

cypress/support/POM/commonPage.js
Added wait for whatsapp icon after cy.reload() so that the page is completely loaded.
Further details in [ticket](https://app.clickup.com/t/20696747/DERC-2434)
=> Fix for Failing Test at Smoke/euFooter.cy.js

cypress/e2e/smoke/rowRegulatory.cy.js
This PR has code for regulatory page
Card details - https://app.clickup.com/t/20696747/DERC-2440
=> regulatory_page

cypress.config.js, cypress/e2e/smoke/signUpCompleteFlow.cy.js, cypress/e2e/wip/signUpCompleteFlow.cy.js, cypress/support/e2e.js
Minor mods to the process, such as ensuring that the correct email link got chosen and the endpoint was set correctly.
=> Signup test

cypress/e2e/full/tradingPlatformMT5.cy.js
This PR has code for mt5 platform page 
card - https://app.clickup.com/t/20696747/DERC-2439
=> mt5 platform

cypress/e2e/full/aboutUsWhyChooseUs.cy.js
This PR has code for why choose us page
=> Why Choose Us

cypress.config.js, cypress/e2e/full/validateAllLinks.cy.js, cypress/e2e/wip/checkAllLinks.cy.js
Refactored logic for checkAllLinks.cy.js to create test for validateAllLinks.cy.js and complete the test. added recursive function for checkLink to traverse through all the links available on homepage as well as all the child pages which fall in the scope of Deriv.com. Adding Checking function to check for certain conditions as well before validating a link and to make sure the recursive function is not stuck in a loop.
The test takes a total time of approximately 7-10 minutes and validates all possible links and child links 
Added comments for each Function created 
two urls which are added in excluded visit and check links are to be removed after fix is provided for them.
Will remove the previous test file wip/checkAllLinks.cy.js once this is approved/merged.
=> Bilal/validate all links for EU, ROW and DIEL

cypress.config.js, cypress/e2e/smoke/euFooter.cy.js, cypress/e2e/smoke/rowFooter.cy.js
In this PR- 
I have included a check for Google Play, App Store, and App Gallery download links, as well as some validation checks for the (ROW). On the other hand, I have made sure that these applications are not available for EU clients.
=> check on app market urls Deriv Go 

cypress/e2e/full/tradingPlatformCtrader.cy.js
- In this PR 
I have included Ctrader coverage, mainly seck on demo and real account. Then Browse FAQ section by expanding and collapsing the accordion. The test script has written according to the checklist of test case scenario.
=> add ctrader coverage

cypress/e2e/full/tradingPlatformDbot.cy.js, cypress/e2e/full/tradingPlatformDtrader.cy.js, cypress/e2e/full/tradingPlatformMT5.cy.js, cypress/support/livepricing.js
This PR has fix for scripts under "full" folder wrt to the new deriv.com home page . Have included fix for livepricing failure
card - https://app.clickup.com/t/86bxdw66a
=> failures_script_fix

cypress/support/livepricing.js
This PR has fix for the failure in EU_livepricing script
=> pricing_fix

cypress/e2e/full/allLocationPage.cy.js, cypress/e2e/full/tradersTool.cy.js
This PR has code for traderstoolmainpage and traderstool-margincalculator page
card - https://app.clickup.com/t/20696747/DERC-2461
https://app.clickup.com/t/20696747/DERC-2455
And in addition i have done code cleanup for allLocationPage script
=> tradersToolPage

cypress/e2e/smoke/allHomeTradeType.cy.js
In this PR 
- I have fixed intermittent issues for the trade type page that have been addressed my @fasihali-deriv and other flaky test issue on trade type script.
Run - https://cloud.cypress.io/projects/16kef2/runs/2438/overview?roarHideRunsWithDiffGroupsAndTags=1
-https://github.com/deriv-com/e2e-deriv-com/actions/runs/7974984281/job/21772115829
=> fix flaky and intermittent test issue for all trade type page 

cypress/e2e/full/tradingPlatformDerivX.cy.js
This PR contains cypress code to verify DerivX product page.
Click up task : https://app.clickup.com/t/20696747/DERC-2424
=> deriv_x_page

cypress/e2e/full/checkAllLanguages.cy.js
Fix for checkAllLanguages, due to the changes of this [card](https://app.clickup.com/t/20696747/DPROD-1802)
=> fix check THAI language

cypress/e2e/smoke/allHomeBanner.cy.js
This PR has update of script for homebanner to include awards check and Trust Pilot
Card - https://app.clickup.com/t/20696747/DERC-2466
=> homebannerupdate

cypress/e2e/smoke/euLivePricing.cy.js, cypress/e2e/smoke/rowLivePricing.cy.js, cypress/support/livepricing.js
This PR has code for including new market in pricing check for both EU and Non EU
Card - https://app.clickup.com/t/20696747/DERC-2467 ,
=> pricingscriptupdate

cypress/e2e/smoke/allHomeBanner.cy.js
Changing the award name from the allHomeBanner.cy.js file from 'Best forex spreads APAC 2023 by UF Awards' to 'Most Innovative Broker, UF Awards 2023'
=> Agrim/fix: changing the award 

cypress/e2e/full_extended/validateAllLinks.cy.js
=> Master failure fix for cypress full extended

cypress/e2e/smoke/livePriceLogin.cy.js
PR - has coverage on responsive for live price "buy" and "sell" button
=> add responsive coverage

cypress/e2e/smoke/allHomeTradeType.cy.js
card - https://app.clickup.com/t/20696747/DERC-2515
This PR has fix for flaky test QATEST-1366 Trade types ROW
=> flakytestfix

cypress/e2e/smoke/allHomePayments.cy.js, cypress/e2e/smoke/dielFooter.cy.js
Card - https://app.clickup.com/t/20696747/DPROD-3812 , https://app.clickup.com/t/20696747/DPROD-3813 
This PR has script for homepage - Payment methods for ROW and EU
=> paymentmethod-smoke

cypress/support/POM/expectedURLs.js
Update expected links based on the  SEO optimisation
https://app.clickup.com/t/20696747/DPROD-56
=> update expected links

cypress/support/POM/expectedURLs.js
Removed telegram from expected list for DIEL counties 
https://app.clickup.com/t/20696747/DPROD-3654
=> remove telegram from DIEL footer

cypress/support/POM/expectedURLs.js
These links removed from EU/ROW footer
https://staging.deriv.com/tnc/risk-disclosure.pdf 
https://staging.deriv.com/regulatory/Deriv(BVI)Ltd.pdf
https://staging.deriv.com/regulatory/Deriv(V)_Ltd.pdf
https://staging.deriv.com/regulatory/Deriv_(FX)Ltd.pdf
https://app.clickup.com/t/20696747/DPROD-3738
https://app.clickup.com/t/20696747/DPROD-3739
=> remove footer links

.github/workflows/cypress_cloud_cron.yml
Integrating Full Tests into Cron Job
https://app.clickup.com/t/20696747/DPROD-3923
=> cron job for full tests

cypress/e2e/full/tradersTool.cy.js
card - https://app.clickup.com/t/20696747/DPROD-3894
this pr has Fix for failure  Traders tool - Margin calculator
=> traderstoolfix

cypress/e2e/smoke/allHomePage.cy.js, cypress/e2e/smoke/allHomePayments.cy.js, cypress/e2e/smoke/euLivePricing.cy.js
card - https://app.clickup.com/t/20696747/DPROD-3998 , https://app.clickup.com/t/20696747/DPROD-3997 https://app.clickup.com/t/20696747/DPROD-4003 
This PR has script for adding the 25 years section in home page and updating the allhomepayments and eulivepricing script based on the new test cases added
=> scriptUpdate

cypress/support/POM/expectedURLs.js
Based on new design, the hyperlink removed from text, hence the code need to be updated. 
https://app.clickup.com/t/20696747/DPROD-3545
=> remove eu link based on new design

cypress/e2e/full/careersHomepage.cy.js
Fix master failures in `careersHomepage`
=> wait for last icon

.github/workflows/webflow_percy.yml
This PR is to add new workflow in github action for Webflow with Percy.
=> webflow percy

cypress/e2e/smoke/rowRegulatory.cy.js
This PR has minor fix in regulatory page failure https://cloud.cypress.io/projects/c4ss4g/runs/66/overview/5cadec53-a201-4ba3-969e-905dd7a43a40?roarHideRunsWithDiffGroupsAndTags=1
=> regulatorypagefix

cypress/e2e/full/careersHomepage.cy.js
full/careersHomepage.cy.js script is failing through gh run because of  not getting loaded properly . 
Have tried approach of wait and and waiting till last element is loaded in page still through GH run is getting failed at times .
So for temporary in this PR have commented the line which is trying to verify the image , will later check work on some other approach to validate this element
=> comment_image-code

cypress/e2e/full/careersHomepage.cy.js
PR has fix for careersHomePageFailure - https://deriv-group.slack.com/archives/C047YVCLCJX/p1716338399483309
workflow - https://cloud.cypress.io/projects/16kef2/runs/3338/overview?roarHideRunsWithDiffGroupsAndTags=1
=> careerspagefailurefix

cypress/e2e/full/tradersTool.cy.js
failure - https://deriv-group.slack.com/archives/C047YVCLCJX/p1717375208254269
=> marginfailurefix

cypress/e2e/full/tradingPlatformDbot.cy.js, cypress/e2e/full/tradingPlatformDtrader.cy.js
Added validation when the clicked on "Go to live demo" it should make sure the link status is not 404
=> add_livedemo_validation
